### PR TITLE
lenovo_motorola: Add loader for TB-J716F XiaoXin Pad P11 Pro

### PR DESCRIPTION
**Pull request by minhng99**
Extracted from TB-J716F_CN_OPEN_USER_Q00209.3_R_ZUI_12.6.211_ST_210730_qpst.zip

Tested on my device, does not support peek/poke sadly :(

### CODE REVIEW

**Comment by lethargy123** [comment]
Excuse me, may I ask how you made this bin file with 9008 package? Because I want to make one for Xiaoxin pad plus (j607f)

**Comment by lethargy123** [comment]
> 摘自 TB-J716F_CN_OPEN_USER_Q00209.3_R_ZUI_12.6.211_ST_210730_qpst.zip
> 
> 在我的设备上测试过，遗憾的是不支持偷看/戳:(

Excuse me, may I ask how you made this bin file with 9008 package? Because I want to make one for Xiaoxin pad plus (j607f)

**Comment by minhng99** [comment]
It's extracted from the leaked qpst firmware

**Comment by bkerler** [comment]
Thanks

**Pull request merged**
